name: preprod

on: 
  push: 
    branches: 
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: "Install PNPM"
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.2 

      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: "Install dependencies"
        run: pnpm install

      - name: Run linter
        run: pnpm run lint
      
      - name: Deploy Vps
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd wizmi_api
            git pull origin develop
            docker-compose stop wizmi_api
            docker-compose rm -f wizmi_api
            docker image rm wizmi_api
            docker-compose up --build -d wizmi_api